### ISSUE TITLE
feature: add character selection menu

### ISSUE THREAD

**Issue by ghost** [rpg-godot/rpg-godot#16]
It would just be a scrolling window that displays some information about the character and a button that allows new characters to be created
Or, if no save is present it just gets you to make your first character
After making a character it should start the game with that character chosen

**Comment by josephtheengineer** [comment]
It would just be a scrolling window that displays some information about the character and a button that allows new characters to be created
Or, if no save is present it just gets you to make your first character
After making a character it should start the game with that character chosen

**Comment by eco9898** [comment]
If you leave a space up the top for a title banner and the game logo next to it, that would be nice.
Just a little bit of space on the top of the scene, like a title bar. Maybe 100px or something, play around a bit with a fake name and one of the attack logos there.
Or we could have a big logo that takes up a bit more space and then the name underneath it.

**Comment by eco9898** [comment]
closed: #57
